/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import conexion.Conexiondb;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Viviana
 */
public class jfPassword extends javax.swing.JFrame {
ResultSet rs;
private PBvalida task01Inf;
    /**
     * Creates new form jfPassword
     */
    public jfPassword() {
        initComponents();
        setLocationRelativeTo(null);
        jp_bar.setVisible(false);
       
    }
    
    public void hideFrame(){
        this.setVisible(false);
    }
    
    public void validar() {
        rs = Conexiondb.Consulta("SELECT USUCVE, USUPAS FROM USUCAT WHERE USUCVE='" + jt_user.getText() + "' AND USUPAS='" + jp_pass.getText() + "'");
        try {
            //ResultSetMetaData rsmt = rs.getMetaData();

            if (rs.next()) {

                String user = rs.getString(1).toString().trim();
                String pass = rs.getString(2).toString().trim();

                String usertxt = jt_user.getText().toUpperCase();
                String passtxt = jp_pass.getText().trim();

                if (user.equals(usertxt) && pass.equals(passtxt)) {
                    jt_user.setText(null);
                    jp_pass.setText(null);

                    hideFrame();
                    MenuPrincipal menuprinc = new MenuPrincipal();
                    menuprinc.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Usuario o Password invalido", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);
                jt_user.setText(null);
                jp_pass.setText(null);
                jt_user.grabFocus();
            }

        } catch (SQLException ex) {
            Logger.getLogger(jfPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jl_user = new javax.swing.JLabel();
        jl_pass = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jt_user = new javax.swing.JTextField();
        jl_logo = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        jp_pass = new javax.swing.JPasswordField();
        jp_bar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jl_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(0, 51, 153));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Credenciales");

        jl_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_user.setText("Usuario:");

        jl_pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_pass.setText("Password:");

        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        btnEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEntrarKeyPressed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jt_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_userKeyTyped(evt);
            }
        });

        jl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/logo cap.png"))); // NOI18N

        btnlimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        jp_pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jp_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jp_passKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jp_bar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_pass)
                            .addComponent(jp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(btnlimpiar)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addComponent(jp_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        jt_user.setText("");
        jp_pass.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if (jt_user.getText().isEmpty() && jp_pass.getText().length() > 0) {
            JOptionPane.showMessageDialog(null, "Ingresa el Usuario", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);
            jt_user.setText(null);
            jp_pass.setText(null);
        } else if (jt_user.getText().isEmpty() && jp_pass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa el Usuario y Password", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);

        } else if (jt_user.getText().length() > 0 && jp_pass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa el Password", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);

        } else if (jt_user.getText().length() > 0 && jp_pass.getText().length() > 0) {
            task01Inf = new PBvalida();
            task01Inf.execute();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jt_user.getText().isEmpty() && jp_pass.getText().length() > 0) {
                JOptionPane.showMessageDialog(null, "Ingresa el Usuario", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);
                jt_user.setText(null);
                jp_pass.setText(null);
            } else if (jt_user.getText().isEmpty() && jp_pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingresa el Usuario y Password", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);

            } else if (jt_user.getText().length() > 0 && jp_pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingresa el Password", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);

            } else if (jt_user.getText().length() > 0 && jp_pass.getText().length() > 0) {
                task01Inf = new PBvalida();
                task01Inf.execute();
            }
        }
    }//GEN-LAST:event_btnEntrarKeyPressed

    private void jp_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp_passKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jt_user.getText().isEmpty() && jp_pass.getText().length() > 0) {
                JOptionPane.showMessageDialog(null, "Ingresa el Usuario", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);
                jt_user.setText(null);
                jp_pass.setText(null);
            } else if (jt_user.getText().isEmpty() && jp_pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingresa el Usuario y Password", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);

            } else if (jt_user.getText().length() > 0 && jp_pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingresa el Password", "Error de Credenciales", JOptionPane.ERROR_MESSAGE);

            } else if (jt_user.getText().length() > 0 && jp_pass.getText().length() > 0) {
                task01Inf = new PBvalida();
                task01Inf.execute();
            }
        }
    }//GEN-LAST:event_jp_passKeyPressed

    private void jt_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_userKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            String cad = ("" + c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }

    }//GEN-LAST:event_jt_userKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel jl_logo;
    private javax.swing.JLabel jl_pass;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JLabel jl_user;
    private javax.swing.JProgressBar jp_bar;
    private javax.swing.JPasswordField jp_pass;
    private javax.swing.JTextField jt_user;
    // End of variables declaration//GEN-END:variables

    class PBvalida extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            jp_bar.setVisible(true);
            jp_bar.setIndeterminate(true);
            validar();
            return null;
        }

        @Override
        protected void done() {
            jp_bar.setVisible(false);
        }
    }
}
