/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Frame;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.UIManager;

/**
 * @author Jessica Viviana Pstrana Munguia
 */
public class MenuPrincipal extends javax.swing.JFrame {

    //private ProgressCajaInf task001Inf;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        jl_titulo.setHorizontalAlignment(JLabel.CENTER);
        jl_logo.setHorizontalAlignment(JLabel.CENTER);
        setResizable(false);
    }
    
    public void hideFrame(){
        this.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jl_titulo = new javax.swing.JLabel();
        jl_logo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jm_reportes = new javax.swing.JMenu();
        jmenu_vacunas = new javax.swing.JMenu();
        jm_item_subliguales = new javax.swing.JMenuItem();
        jm_item_Inyectadas = new javax.swing.JMenuItem();
        jm_item_expediente = new javax.swing.JMenuItem();
        jm_item_vac_totales = new javax.swing.JMenuItem();
        jmenu_inhalos = new javax.swing.JMenu();
        jm_item_inhalo_totales = new javax.swing.JMenuItem();
        jmenu_consultas = new javax.swing.JMenu();
        jm_item_cons_prim_vez = new javax.swing.JMenuItem();
        jm_item_consulta_subsecuentes = new javax.swing.JMenuItem();
        jmenu_pruebas = new javax.swing.JMenu();
        jm_item_cutanea_fec = new javax.swing.JMenuItem();
        jm_item_cutanea_exp = new javax.swing.JMenuItem();
        jm_caja = new javax.swing.JMenu();
        jmenu_caja = new javax.swing.JMenuItem();
        jmenu_conceptos = new javax.swing.JMenuItem();
        jmenu_descuentos = new javax.swing.JMenu();
        jmenu_item_desc = new javax.swing.JMenuItem();
        jmenu_item_cve_exp = new javax.swing.JMenuItem();
        jmenu_item_aplicar_desc = new javax.swing.JMenuItem();
        jm_salir = new javax.swing.JMenu();
        jm_item_salir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reportes Clinica");

        jl_titulo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(153, 0, 153));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Clínica de Alergia Pediátrica");

        jl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/logo-cap.png"))); // NOI18N

        jm_reportes.setBorder(null);
        jm_reportes.setForeground(new java.awt.Color(102, 0, 102));
        jm_reportes.setMnemonic('R');
        jm_reportes.setText("Reportes");
        jm_reportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jm_reportes.setPreferredSize(new java.awt.Dimension(95, 28));

        jmenu_vacunas.setMnemonic('v');
        jmenu_vacunas.setText("Vacunas");
        jmenu_vacunas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jm_item_subliguales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jm_item_subliguales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_subliguales.setMnemonic('l');
        jm_item_subliguales.setText("Vacunas Sublinguales");
        jm_item_subliguales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_subligualesActionPerformed(evt);
            }
        });
        jmenu_vacunas.add(jm_item_subliguales);

        jm_item_Inyectadas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.ALT_MASK));
        jm_item_Inyectadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_Inyectadas.setMnemonic('y');
        jm_item_Inyectadas.setText("Vacunas Inyectadas");
        jm_item_Inyectadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_InyectadasActionPerformed(evt);
            }
        });
        jmenu_vacunas.add(jm_item_Inyectadas);

        jm_item_expediente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jm_item_expediente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_expediente.setMnemonic('e');
        jm_item_expediente.setText("Vacunas por Expediente");
        jm_item_expediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_expedienteActionPerformed(evt);
            }
        });
        jmenu_vacunas.add(jm_item_expediente);

        jm_item_vac_totales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jm_item_vac_totales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_vac_totales.setMnemonic('t');
        jm_item_vac_totales.setText("Vacunas Totales");
        jm_item_vac_totales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_vac_totalesActionPerformed(evt);
            }
        });
        jmenu_vacunas.add(jm_item_vac_totales);

        jm_reportes.add(jmenu_vacunas);

        jmenu_inhalos.setMnemonic('i');
        jmenu_inhalos.setText("Inhaloterapias");
        jmenu_inhalos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jm_item_inhalo_totales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jm_item_inhalo_totales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_inhalo_totales.setMnemonic('n');
        jm_item_inhalo_totales.setText("Por Fecha Tratamiento y Nombre");
        jm_item_inhalo_totales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_inhalo_totalesActionPerformed(evt);
            }
        });
        jmenu_inhalos.add(jm_item_inhalo_totales);

        jm_reportes.add(jmenu_inhalos);

        jmenu_consultas.setMnemonic('o');
        jmenu_consultas.setText("Consultas");
        jmenu_consultas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jm_item_cons_prim_vez.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jm_item_cons_prim_vez.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_cons_prim_vez.setMnemonic('p');
        jm_item_cons_prim_vez.setText("Primera Vez");
        jm_item_cons_prim_vez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_cons_prim_vezActionPerformed(evt);
            }
        });
        jmenu_consultas.add(jm_item_cons_prim_vez);

        jm_item_consulta_subsecuentes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jm_item_consulta_subsecuentes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_consulta_subsecuentes.setMnemonic('b');
        jm_item_consulta_subsecuentes.setText("Subsecuentes");
        jm_item_consulta_subsecuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_consulta_subsecuentesActionPerformed(evt);
            }
        });
        jmenu_consultas.add(jm_item_consulta_subsecuentes);

        jm_reportes.add(jmenu_consultas);

        jmenu_pruebas.setMnemonic('u');
        jmenu_pruebas.setText("Pruebas Cutáneas");
        jmenu_pruebas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jm_item_cutanea_fec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jm_item_cutanea_fec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_cutanea_fec.setMnemonic('f');
        jm_item_cutanea_fec.setText("Por Fecha");
        jm_item_cutanea_fec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_cutanea_fecActionPerformed(evt);
            }
        });
        jmenu_pruebas.add(jm_item_cutanea_fec);

        jm_item_cutanea_exp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jm_item_cutanea_exp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_cutanea_exp.setMnemonic('x');
        jm_item_cutanea_exp.setText("Por Expediente");
        jm_item_cutanea_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_cutanea_expActionPerformed(evt);
            }
        });
        jmenu_pruebas.add(jm_item_cutanea_exp);

        jm_reportes.add(jmenu_pruebas);

        jMenuBar.add(jm_reportes);

        jm_caja.setBorder(null);
        jm_caja.setForeground(new java.awt.Color(0, 0, 102));
        jm_caja.setMnemonic('c');
        jm_caja.setText("Caja");
        jm_caja.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jm_caja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jm_caja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jm_caja.setPreferredSize(new java.awt.Dimension(55, 28));

        jmenu_caja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK));
        jmenu_caja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmenu_caja.setMnemonic('j');
        jmenu_caja.setText("Corte de Caja");
        jmenu_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_cajaActionPerformed(evt);
            }
        });
        jm_caja.add(jmenu_caja);

        jmenu_conceptos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jmenu_conceptos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmenu_conceptos.setMnemonic('n');
        jmenu_conceptos.setText("Reporte de Conceptos");
        jmenu_conceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_conceptosActionPerformed(evt);
            }
        });
        jm_caja.add(jmenu_conceptos);

        jmenu_descuentos.setMnemonic('d');
        jmenu_descuentos.setText("Descuentos");
        jmenu_descuentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmenu_item_desc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jmenu_item_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmenu_item_desc.setMnemonic('a');
        jmenu_item_desc.setText("Por Fecha/Detalle");
        jmenu_item_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_item_descActionPerformed(evt);
            }
        });
        jmenu_descuentos.add(jmenu_item_desc);

        jmenu_item_cve_exp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jmenu_item_cve_exp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmenu_item_cve_exp.setMnemonic('o');
        jmenu_item_cve_exp.setText("Por Expediente/Clave");
        jmenu_item_cve_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_item_cve_expActionPerformed(evt);
            }
        });
        jmenu_descuentos.add(jmenu_item_cve_exp);

        jmenu_item_aplicar_desc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_MASK));
        jmenu_item_aplicar_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmenu_item_aplicar_desc.setText("Aplicar Descuentos");
        jmenu_item_aplicar_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_item_aplicar_descActionPerformed(evt);
            }
        });
        jmenu_descuentos.add(jmenu_item_aplicar_desc);

        jm_caja.add(jmenu_descuentos);

        jMenuBar.add(jm_caja);

        jm_salir.setBorder(null);
        jm_salir.setForeground(new java.awt.Color(0, 102, 0));
        jm_salir.setMnemonic('s');
        jm_salir.setText("Salir");
        jm_salir.setFocusable(false);
        jm_salir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jm_salir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jm_salir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jm_salir.setMaximumSize(new java.awt.Dimension(55, 32767));
        jm_salir.setPreferredSize(new java.awt.Dimension(55, 28));

        jm_item_salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jm_item_salir.setMnemonic('s');
        jm_item_salir.setText("Salir");
        jm_item_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_salirActionPerformed(evt);
            }
        });
        jm_salir.add(jm_item_salir);

        jMenuBar.add(jm_salir);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jl_logo.getAccessibleContext().setAccessibleName("jl_logo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_item_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jm_item_salirActionPerformed

    private void jm_item_inhalo_totalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_inhalo_totalesActionPerformed
        jfInhalos frmInhalos = new jfInhalos();
        frmInhalos.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_inhalo_totalesActionPerformed

    private void jm_item_subligualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_subligualesActionPerformed
        jfVSublingual frmSublingual = new jfVSublingual();
        frmSublingual.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_subligualesActionPerformed

    private void jm_item_InyectadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_InyectadasActionPerformed
        jfVInyectadas frmInyectadas = new jfVInyectadas();
        frmInyectadas.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_InyectadasActionPerformed

    private void jm_item_expedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_expedienteActionPerformed
        jfVExpediente frmVExpediente = new jfVExpediente();
        frmVExpediente.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_expedienteActionPerformed

    private void jm_item_vac_totalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_vac_totalesActionPerformed
        jfVTotales frmvTotales = new jfVTotales();
        frmvTotales.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_vac_totalesActionPerformed

    private void jm_item_consulta_subsecuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_consulta_subsecuentesActionPerformed
        jfCSubsecuentes frmcSubSec = new jfCSubsecuentes();
        frmcSubSec.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_consulta_subsecuentesActionPerformed

    private void jm_item_cons_prim_vezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_cons_prim_vezActionPerformed
        jfCPrimeraVez frmcPrimVez = new jfCPrimeraVez();
        frmcPrimVez.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_cons_prim_vezActionPerformed

    private void jm_item_cutanea_fecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_cutanea_fecActionPerformed
        jfPCutanea frmpCutanea = new jfPCutanea();
        frmpCutanea.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_cutanea_fecActionPerformed

    private void jm_item_cutanea_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_cutanea_expActionPerformed
        jfpCutaneaExp frmpCutaneaexp = new jfpCutaneaExp();
        frmpCutaneaexp.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jm_item_cutanea_expActionPerformed

    private void jmenu_conceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_conceptosActionPerformed
        jfCajaConceptos frmCajaConceptos = new jfCajaConceptos();
        frmCajaConceptos.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jmenu_conceptosActionPerformed

    private void jmenu_item_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_item_descActionPerformed
        jfCajaDescuentos frmCajaDescuentos = new jfCajaDescuentos();
        frmCajaDescuentos.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jmenu_item_descActionPerformed

    private void jmenu_item_cve_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_item_cve_expActionPerformed
        jfCajaExpCve frmCajaExpcve = new jfCajaExpCve();
        frmCajaExpcve.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jmenu_item_cve_expActionPerformed

    private void jmenu_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_cajaActionPerformed
        jfCorteCaja1 frmCorteCaja = new jfCorteCaja1();
        frmCorteCaja.setVisible(true);
        hideFrame();
        //task001Inf = new ProgressCajaInf();
        //task001Inf.execute();
        
    }//GEN-LAST:event_jmenu_cajaActionPerformed

    private void jmenu_item_aplicar_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_item_aplicar_descActionPerformed
        jfAplicarDescuento frmAplicaDesc = new jfAplicarDescuento();
        frmAplicaDesc.setVisible(true);
        hideFrame();
    }//GEN-LAST:event_jmenu_item_aplicar_descActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
        SwingUtilities.invokeLater(new Runnable(){
            public void run() {
                try{
                    UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
                }catch(Exception e){
                    e.printStackTrace();
                }
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JLabel jl_logo;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JMenu jm_caja;
    private javax.swing.JMenuItem jm_item_Inyectadas;
    private javax.swing.JMenuItem jm_item_cons_prim_vez;
    private javax.swing.JMenuItem jm_item_consulta_subsecuentes;
    private javax.swing.JMenuItem jm_item_cutanea_exp;
    private javax.swing.JMenuItem jm_item_cutanea_fec;
    private javax.swing.JMenuItem jm_item_expediente;
    private javax.swing.JMenuItem jm_item_inhalo_totales;
    private javax.swing.JMenuItem jm_item_salir;
    private javax.swing.JMenuItem jm_item_subliguales;
    private javax.swing.JMenuItem jm_item_vac_totales;
    private javax.swing.JMenu jm_reportes;
    private javax.swing.JMenu jm_salir;
    private javax.swing.JMenuItem jmenu_caja;
    private javax.swing.JMenuItem jmenu_conceptos;
    private javax.swing.JMenu jmenu_consultas;
    private javax.swing.JMenu jmenu_descuentos;
    private javax.swing.JMenu jmenu_inhalos;
    private javax.swing.JMenuItem jmenu_item_aplicar_desc;
    private javax.swing.JMenuItem jmenu_item_cve_exp;
    private javax.swing.JMenuItem jmenu_item_desc;
    private javax.swing.JMenu jmenu_pruebas;
    private javax.swing.JMenu jmenu_vacunas;
    // End of variables declaration//GEN-END:variables
}
